# Generated by Django 5.2.1 on 2025-06-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subreddit', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query Comment',
                'verbose_name_plural': 'Query Comments',
                'db_table': 'query_comments',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_utc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='comments',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ingester.querycomments'),
        ),
    ]
