# Generated by Django 5.2.1 on 2025-06-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingester', '0002_querycomments_alter_comments_created_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycomments',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
