# Generated by Django 4.1.12 on 2026-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingester', '0004_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
