# Generated by Django 4.1.12 on 2026-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingester', '0005_alter_comments_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
