# Generated by Django 4.1.12 on 2026-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingester', '0006_alter_comments_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
